[LOGGING]
log_retention_days = 7
log_directory = logs
# DEBUG,INFO,WARNING,ERROR
log_level = INFO
debug_mode = True
project_name = KeepDrive

[KEEP] # メモタイトル = 結合先ドキュメントURL
人間関係 = https://docs.google.com/document/d/1IUgy5pnvJSuYOSDdKHUCX9iVO1M-typzg6q__vriyHQ/edit?tab=t.0
運動 = https://docs.google.com/document/d/1ryFpZe3jds0wCF22BG5VrD5hQSASTUK-JOR2zLi1Els/edit?tab=t.0
健康 = https://docs.google.com/document/d/1MAhCvl3UtjAWUr3WcH4NUJdtto9zVXfrTJv7jWJAOwY/edit?tab=t.0
資産運用 = https://docs.google.com/document/d/1_lf8xhNuwujcUbeIUcHE0PL1ok48bIA6vsmfNeIkYiE/edit?tab=t.0
掃除 = https://docs.google.com/document/d/1FWu26E1QhlZsHTzNrQuGglI59nRxam7RZ7x8EZW0JAk/edit?tab=t.0
開発 = https://docs.google.com/document/d/1slqt0Q_u0DnW-3BM2AN1h-WAnJ83HVPBKAGPb1f-PGc/edit?tab=t.0
情報 = https://docs.google.com/document/d/1I0ci7K4ClIWg85eIXTADxrT1AGs-TAzlehnqp-rKHb4/edit?tab=t.0
身だしなみ = https://docs.google.com/document/d/1Gyh8M1smei02gwWhsxNro12UhfyLkzUjzq8RJCHlyZ4/edit?tab=t.0
