[LOGGING]
log_retention_days = 7
log_directory = logs
# DEBUG,INFO,WARNING,ERROR
log_level = INFO
debug_mode = True
project_name = KeepDrive

[KEEP]
# 取り込むリスト名をカンマ区切りで指定する。空欄の場合は全リストを対象にする
# 例: target_lists = 読書,ショッピング,生活
target_lists =資産運用

