[LOGGING]
log_retention_days = 7
log_directory = logs
# DEBUG,INFO,WARNING,ERROR
log_level = INFO
debug_mode = True
project_name = KeepDrive

[KEEP]
# メモタイトル = 結合先ドキュメントURL
人間関係 = https://keep.google.com/u/0/#NOTE/1KFUxb9Cl7qdhXTgJsXiJ-VDTvXbbzMXY_mqBCUwxCS0MXKB0iZzx_5K0m_M9mg
